name: telegram_scraping

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs: 
  telegram_scraping_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Telegram monitor
    - run: Rscript source("R/twitter_monitor.R")
