name: tweets update 

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  status-check:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Get the status of google.com'
        uses: im-open/url-status-check@v1.1.1
        with:
          url: 'https://smallarmssurvey.shinyapps.io/afg_tweets_download/'
          fail-on-bad-status: false

