name: Update tweets test

on:
   schedule:
   - cron: "0 0 * * *"
   workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest
      
      - name: Open chrome
        run: |
          $Env:CHROME_BIN = 'c:\hostedtoolcache\windows\chromium\latest\x64\chrome.exe'
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Load packages 
        run: |
          install.packages(c("tidyverse", "tibble", "data.table", "rtweet", "webshot2", "pagedown", "chromote", "cld2", "googleLanguageR", "googledrive", "googlesheets4", "sf", "htmltools"))
        shell: Rscript {0}

      - name: Update data
        run: |
          source("R/tweets_download_test.R")
        shell: Rscript {0}
        env:
          BEARER: ${{ secrets.TWITTER_BEARER }}
