name: tweets update 

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs: 
  update:
    runs-on: ubuntu-latest
    steps:
      - name: update tweets
        uses: im-open/url-status-check@v1.1.1
        with:
          url: "www.gazzetta.it"
          fail-on-bad-status: false
