name: tweets update 

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs: 
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 'update tweets'
        uses: im-open/url-status-check@v1.1.1
        with:
          url: 'https://smallarmssurvey.shinyapps.io/afg_tweets_download/'
          fail-on-bad-status: false
