name: Update tweets

on:
  # schedule:
  # - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest
      
      - name: Open chrome
        run: |
          $Env:CHROME_BIN = 'c:\hostedtoolcache\windows\chromium\latest\x64\chrome.exe'

      - name: Update data
        run: |
          source("R/tweets_download.R")
        shell: Rscript {0}
