name: Update tweets

on:
  # schedule:
  # - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest
      
      - name: Update data
         xdg-open 'http://www.freedesktop.org/'

