name: tweets update 

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs: 
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: tweets update
      run: xdg-open 'https://smallarmssurvey.shinyapps.io/afg_tweets_download/'
