name: tweets update 

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs: 
  update:
    runs-on: ubuntu-latest
    steps:
      - name: update tweets
        xdg-open 'hwww.gazzetta.it'
