name: tweets update 

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: ${{ ' https://smallarmssurvey.shinyapps.io/afg_tweets_download/' }}
      METHOD: GET
    steps:
      - id: ping
        uses: sisodiya2421/pinger@v3
